# Generated by Django 4.1.7 on 2023-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('lower_bound', models.IntegerField()),
                ('upper_bound', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
