# Generated by Django 4.1.7 on 2023-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='month',
        ),
        migrations.AddField(
            model_name='geodata',
            name='mean',
            field=models.IntegerField(default=0),
        ),
    ]
