# Generated by Django 4.1.7 on 2023-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
